### PR TITLE
[mobile] [basic configuration of client's app]

### PR DESCRIPTION
**Pull request by ybaa**

### CODE REVIEW

**Review by pwr218154 — COMMENTED** [review]
Perhaps assets could be placed in client apps directory and linked into project?

**Comment by ybaa** [comment]
I tried to place assets in client app directory but it doesn't work. It can't be placed in higher directory than app.json

**Review by pwr218154 — APPROVED** [review]
Ok for me it is ok. Thanks for trying, If you wouldnt  mind i will try to configure assets as external sources. Lets merge it.

**Comment by ybaa** [comment]
@swojciechowski  fell free to try

**Pull request merged**
